title = "MastCar"
baseURL = ""
languageCode = "en-gb"
theme = "hugo-scroll"

disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#googleAnalytics = ""
enableRobotsTXT = false

relativeURLS = true

[params]
  favicon = ""
  description = "Amateur radio tactical response vehicle"
  title = "Mastcar - Amateur radio tactical response vehicle"
  hidedesignbyline = true
